/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    services: Service;
    pages: Page;
    inquiries: Inquiry;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    inquiries: InquiriesSelect<false> | InquiriesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'es') | ('en' | 'es')[];
  globals: {
    header: Header;
    'transparency-panel': TransparencyPanel;
    hero: Hero;
    'services-section': ServicesSection;
    'process-section': ProcessSection;
    footer: Footer;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    'transparency-panel': TransparencyPanelSelect<false> | TransparencyPanelSelect<true>;
    hero: HeroSelect<false> | HeroSelect<true>;
    'services-section': ServicesSectionSelect<false> | ServicesSectionSelect<true>;
    'process-section': ProcessSectionSelect<false> | ProcessSectionSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: 'en' | 'es';
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  /**
   * URL-safe identifier, e.g. "payload", "umbraco", "wordpress"
   */
  slug: string;
  /**
   * Tab label shown to users, e.g. "Payload CMS"
   */
  label: string;
  icon: 'Database' | 'Layers' | 'Code' | 'Server' | 'Activity' | 'Cpu';
  /**
   * Heading inside the content panel
   */
  title: string;
  /**
   * Accent subtitle shown in teal highlight bar
   */
  subtitle: string;
  description: string;
  /**
   * Text shown in the dark "Agentic Edge" panel
   */
  agenticEdge: string;
  /**
   * Rows in the "Deployment Specs" table
   */
  specs?:
    | {
        label: string;
        value: string;
        icon: 'Server' | 'Activity' | 'ShieldCheck' | 'Database';
        accentColor: 'deep-ink' | 'plasma-teal' | 'holo-lilac';
        id?: string | null;
      }[]
    | null;
  /**
   * List items shown in "Bespoke Plugins & Integrations"
   */
  plugins?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Controls tab display order (lower numbers appear first)
   */
  order: number;
  /**
   * Hero image shown on the service detail page
   */
  featuredImage?: (number | null) | Media;
  /**
   * Extended content shown on the individual service page (/services/[slug])
   */
  detailContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL path for this page, e.g. "about" becomes /about
   */
  slug: string;
  meta?: {
    /**
     * Override the page title for SEO (defaults to page title)
     */
    metaTitle?: string | null;
    /**
     * Meta description for search engines
     */
    metaDescription?: string | null;
  };
  layout?:
    | (
        | {
            heading: string;
            body: string;
            /**
             * Call-to-action button label
             */
            ctaText?: string | null;
            /**
             * URL or path for the CTA button
             */
            ctaLink?: string | null;
            /**
             * Show the 3D prism animation
             */
            showPrism?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero-block';
          }
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'content-block';
          }
        | {
            heading: string;
            body?: string | null;
            buttonText: string;
            buttonLink: string;
            style?: ('dark' | 'teal') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta-block';
          }
        | {
            heading?: string | null;
            cards?:
              | {
                  title: string;
                  description: string;
                  icon?: ('Database' | 'Layers' | 'Code' | 'Server' | 'Activity' | 'ShieldCheck' | 'Cpu') | null;
                  /**
                   * Optional URL or path
                   */
                  link?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'card-grid-block';
          }
        | {
            heading?: string | null;
            intro?: string | null;
            /**
             * Show "Learn More" links to individual service pages
             */
            showDetailLinks?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'services-overview-block';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Contact form submissions
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries".
 */
export interface Inquiry {
  id: number;
  name: string;
  email: string;
  message: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'inquiries';
        value: number | Inquiry;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  slug?: T;
  label?: T;
  icon?: T;
  title?: T;
  subtitle?: T;
  description?: T;
  agenticEdge?: T;
  specs?:
    | T
    | {
        label?: T;
        value?: T;
        icon?: T;
        accentColor?: T;
        id?: T;
      };
  plugins?:
    | T
    | {
        text?: T;
        id?: T;
      };
  order?: T;
  featuredImage?: T;
  detailContent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  meta?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  layout?:
    | T
    | {
        'hero-block'?:
          | T
          | {
              heading?: T;
              body?: T;
              ctaText?: T;
              ctaLink?: T;
              showPrism?: T;
              id?: T;
              blockName?: T;
            };
        'content-block'?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        'cta-block'?:
          | T
          | {
              heading?: T;
              body?: T;
              buttonText?: T;
              buttonLink?: T;
              style?: T;
              id?: T;
              blockName?: T;
            };
        'card-grid-block'?:
          | T
          | {
              heading?: T;
              cards?:
                | T
                | {
                    title?: T;
                    description?: T;
                    icon?: T;
                    link?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'services-overview-block'?:
          | T
          | {
              heading?: T;
              intro?: T;
              showDetailLinks?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries_select".
 */
export interface InquiriesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  logoText: string;
  /**
   * The accent character rendered in plasma teal after logoText
   */
  logoAccent: string;
  navLinks?:
    | {
        label: string;
        linkType?: ('custom' | 'page') | null;
        /**
         * URL or anchor link (e.g. #services, /contact)
         */
        href?: string | null;
        /**
         * Select an internal page
         */
        page?: (number | null) | Page;
        id?: string | null;
      }[]
    | null;
  oversightLabel: string;
  oversightActiveText: string;
  oversightDisabledText: string;
  oversightTooltip: string;
  ctaButtonText: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transparency-panel".
 */
export interface TransparencyPanel {
  id: number;
  /**
   * The typewriter message shown in the transparency bar
   */
  message: string;
  linkText: string;
  linkUrl: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero".
 */
export interface Hero {
  id: number;
  headlinePart1: string;
  /**
   * The italic portion of the headline rendered on a second line
   */
  headlineEmphasis: string;
  bodyText: string;
  ctaButtonText: string;
  ctaButtonUrl: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services-section".
 */
export interface ServicesSection {
  id: number;
  sectionHeadlinePart1: string;
  /**
   * Italic line shown below the main headline
   */
  sectionHeadlineEmphasis: string;
  sectionIntroText: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "process-section".
 */
export interface ProcessSection {
  id: number;
  headline: string;
  headlineEmphasis: string;
  steps: {
    /**
     * Step number, e.g. "01"
     */
    number: string;
    title: string;
    description: string;
    /**
     * Lucide icon name
     */
    icon: string;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  logoText: string;
  logoAccent: string;
  tagline: string;
  footerLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logoText?: T;
  logoAccent?: T;
  navLinks?:
    | T
    | {
        label?: T;
        linkType?: T;
        href?: T;
        page?: T;
        id?: T;
      };
  oversightLabel?: T;
  oversightActiveText?: T;
  oversightDisabledText?: T;
  oversightTooltip?: T;
  ctaButtonText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transparency-panel_select".
 */
export interface TransparencyPanelSelect<T extends boolean = true> {
  message?: T;
  linkText?: T;
  linkUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero_select".
 */
export interface HeroSelect<T extends boolean = true> {
  headlinePart1?: T;
  headlineEmphasis?: T;
  bodyText?: T;
  ctaButtonText?: T;
  ctaButtonUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services-section_select".
 */
export interface ServicesSectionSelect<T extends boolean = true> {
  sectionHeadlinePart1?: T;
  sectionHeadlineEmphasis?: T;
  sectionIntroText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "process-section_select".
 */
export interface ProcessSectionSelect<T extends boolean = true> {
  headline?: T;
  headlineEmphasis?: T;
  steps?:
    | T
    | {
        number?: T;
        title?: T;
        description?: T;
        icon?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  logoText?: T;
  logoAccent?: T;
  tagline?: T;
  footerLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}