<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <CompressionEnabled>false</CompressionEnabled> <!-- Disable compression. E.g. for umbraco backoffice files. These files should be precompressed by node and not let dotnet handle it -->
  </PropertyGroup>

  <ItemGroup>
    <!-- <PackageReference Include="SeoToolkit.Umbraco" Version="5.1.0-beta2" /> -->
    <PackageReference Include="Umbraco.Cms" Version="17.0.0-beta" />
    <PackageReference Include="Umbraco.Cms.DevelopmentMode.Backoffice" Version="17.0.0-beta" />
    <!-- <PackageReference Include="uSync" Version="16.0.8" /> -->
  </ItemGroup>

  <ItemGroup>
    <!-- Opt-in to app-local ICU to ensure consistent globalization APIs across different platforms -->
    <PackageReference Include="Microsoft.ICU.ICU4C.Runtime" Version="72.1.0.3" />
    <RuntimeHostConfigurationOption Include="System.Globalization.AppLocalIcu" Value="72.1.0.3" Condition="$(RuntimeIdentifier.StartsWith('linux')) or $(RuntimeIdentifier.StartsWith('win')) or ('$(RuntimeIdentifier)' == '' and !$([MSBuild]::IsOSPlatform('osx')))" />
  </ItemGroup>

  <ItemGroup>
    <_ContentIncludedByDefault Remove="uSync\v16\Content\about.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\Content\about_xbgat4tl.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\Content\automating-block-rendering-with-razor-partials.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\Content\blog.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\Content\building-modern-digital-experiences-how-we-created-the-nubis-digital-website.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\Content\building-modern-digital-experiences-how-we-created-the-nubis-digital-website_1vtl5iwo.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\Content\composing-the-generic-page-builder.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\Content\contact.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\Content\crafting-the-nubis-block-grid.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\Content\designing-the-glassmorphic-hero.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\Content\engineering-the-nubis-navigation-system.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\Content\home.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\Content\home_gxwacpiu.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\Content\nubis-digital.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\Content\optimizing-block-rendering-performance.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\Content\optimizing-cta-journeys-with-content-pickers.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\Content\pages.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\Content\pages_aojpkrba.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\Content\publishing-the-nubis-site-structure.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\Content\refining-the-about-services-and-contact-experience.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\Content\services.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\Content\site-settings.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\Content\tailwind-variables-for-dual-themes.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\Content\test-page.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\Content\top-5-umbraco-features-perfect-for-newark-tech-startups.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\Content\umbraco-vs-wordpress-why-east-coast-enterprises-choose-umbraco.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\Content\why-new-jersey-businesses-are-choosing-umbraco-cms-in-2025.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\ContentTypes\blockgridlayoutsettings.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\ContentTypes\blogcodeblock.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\ContentTypes\blogheadlineblock.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\ContentTypes\blogimageblock.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\ContentTypes\bloglist.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\ContentTypes\blogpost.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\ContentTypes\blogquoteblock.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\ContentTypes\blogrichtextblock.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\ContentTypes\calltoactionelement.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\ContentTypes\contactformelement.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\ContentTypes\genericpage.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\ContentTypes\herobannerelement.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\ContentTypes\heroslideitem.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\ContentTypes\herosliderelement.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\ContentTypes\homepage.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\ContentTypes\informationalsectionelement.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\ContentTypes\latestblogpostselement.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\ContentTypes\pages.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\ContentTypes\seometadata.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\ContentTypes\serviceitem.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\ContentTypes\servicesoverviewelement.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\ContentTypes\siteroot.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\ContentTypes\sitesettings.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\ContentTypes\standardpage.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\ContentTypes\test.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\ContentTypes\testpage.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\DataTypes\ApprovedColor.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\DataTypes\BlogContentGrid.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\DataTypes\CheckboxList.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\DataTypes\CodeSnippetEditor.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\DataTypes\ContentPicker.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\DataTypes\CTAStyleDropdown.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\DataTypes\DatePicker.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\DataTypes\DatePickerWithTime.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\DataTypes\Dropdown.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\DataTypes\DropdownMultiple.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\DataTypes\GenericPageBlocks.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\DataTypes\HeadingLevel.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\DataTypes\HeroSliderVariant.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\DataTypes\HeroSlidesBlockList.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\DataTypes\HeroStyleDropdown.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\DataTypes\HomePageBlocks.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\DataTypes\ImageCropper.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\DataTypes\ImageMediaPicker.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\DataTypes\LabelBigint.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\DataTypes\LabelBytes.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\DataTypes\LabelDatetime.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\DataTypes\LabelDecimal.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\DataTypes\LabelInteger.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\DataTypes\LabelPixels.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\DataTypes\LabelString.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\DataTypes\LabelTime.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\DataTypes\ListViewContent.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\DataTypes\ListViewMedia.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\DataTypes\MediaPicker.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\DataTypes\MemberPicker.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\DataTypes\MultipleImageMediaPicker.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\DataTypes\MultipleMediaPicker.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\DataTypes\MultiURLPicker.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\DataTypes\Numeric.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\DataTypes\Radiobox.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\DataTypes\RichtextEditor.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\DataTypes\ServiceIconDropdown.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\DataTypes\ServiceItemsBlockList.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\DataTypes\ServicesStyleDropdown.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\DataTypes\Tags.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\DataTypes\testAsDecimalPropertyEditorUI.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\DataTypes\Textarea.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\DataTypes\Textstring.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\DataTypes\Truefalse.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\DataTypes\UploadArticle.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\DataTypes\UploadAudio.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\DataTypes\UploadFile.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\DataTypes\UploadVectorGraphics.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\DataTypes\UploadVideo.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\Domains\en_en-us.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\Domains\es_es-do.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\Domains\_en-us.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\Languages\en-us.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\Languages\es-do.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\Media\0d83dcec-1e15-48d7-813e-9028c56e5a16_1_105_c.tif.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\Media\1ada628a693c2e1f23f752030cd16a8e.jpg.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\Media\gemini_generated_image_ds1tjsds1tjsds1t.png-1.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\Media\gemini_generated_image_ds1tjsds1tjsds1t.png.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\Media\photo-1553877522-43269d4ea984.jpeg.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\Media\premium_photo-1661764256397-af154e87b1b3.avif.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\MediaTypes\file.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\MediaTypes\folder.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\MediaTypes\image.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\MediaTypes\umbracomediaarticle.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\MediaTypes\umbracomediaaudio.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\MediaTypes\umbracomediavectorgraphics.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\MediaTypes\umbracomediavideo.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\MemberTypes\member.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\RelationTypes\umbMember.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\Templates\bloglist.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\Templates\blogpost.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\Templates\genericpage.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\Templates\homepage.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\Templates\standardpage.config" />
    <_ContentIncludedByDefault Remove="uSync\v16\usync.config" />
  </ItemGroup>

  <PropertyGroup>
    <!-- Razor files are needed for the backoffice to work correctly -->
    <CopyRazorGenerateFilesToPublishDirectory>true</CopyRazorGenerateFilesToPublishDirectory>
  </PropertyGroup>

  <PropertyGroup>
    <!-- Remove RazorCompileOnBuild and RazorCompileOnPublish when not using ModelsMode InMemoryAuto -->
    <RazorCompileOnBuild>false</RazorCompileOnBuild>
    <RazorCompileOnPublish>false</RazorCompileOnPublish>
  </PropertyGroup>

</Project>
